config/routes.rb
Rails.application.routes.draw do
  scope(path_names: { new: 'criar', edit: 'editar' }) do
    
    scope module: :landing_page do
      root to: 'static_pages#landing_page'
    end

    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy', as: 'logout'
    
    get 'usuarios/:id/alteracao-de-senha', to: "users#change_password"
    post 'usuarios/:id/alteracao-de-senha', to: "users#change_password", as: 'change_password'
    get 'usuarios/:id/selecao-de-pacote', to: "users#term_agreement"
    post 'usuarios/:id/selecao-de-pacote', to: "users#term_agreement", as: 'term_agreement'
    
    resources :users, path: 'usuarios'
    resources :interests, path: 'juros'
    resources :parcels, path: 'parcelas'
      post '/parcelas/update_status', to: 'parcels#update_status', as: 'update_parcel_status'
    resources :payments, path: 'pagamentos'
      get '/retorna_parcelas', to: 'payments#get_parcelas'
    resources :packages, path: 'pacotes'
    resources :ies, path: 'instituicoes-de-ensino-superior'
    resources :lots, path: 'lotes'
    
    scope module: :landing_page do
      get '/edicao-secoes', to: 'static_pages#sections_edit', as: 'sections_edit'
      post '/contato/enviar-email', to: 'static_pages#send_email', as: 'send_contact_email'
      resources :sponsors_and_supporters_titles, path: 'titulo-de-patrocionadores-e-apoiadores'
      resources :event_realizers_titles, path: 'titulo-de-realizadores-do-evento'
      resources :sponsors_and_supporters, path: 'patrocionadores-e-apoiadores'
      resources :event_realizers, path: 'realizadores-do-evento'
      resources :merchandising_videos, path: 'video-de-divulgacao'
      resources :event_notices, path: 'noticias-do-evento'
      resources :the_speakers, path: 'palestrantes'
      resources :airfares, path: 'passagens-aereas'
      resources :the_events, path: 'eventos'
      resources :showcases, path: 'vitrine'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/landing_page.rb
module LandingPage
    def self.use_relative_model_naming?
        true
    end
end

app/models/landing_page/airfare.rb
class LandingPage::Airfare < ApplicationRecord
end

app/models/landing_page/event_notice.rb
class LandingPage::EventNotice < ApplicationRecord
    mount_uploader :image, ImageUploader
    mount_uploader :document, DocumentUploader
end

app/models/landing_page/event_realizer.rb
class LandingPage::EventRealizer < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/landing_page/event_realizers_title.rb
class LandingPage::EventRealizersTitle < ApplicationRecord
end

app/models/landing_page/merchandising_video.rb
class LandingPage::MerchandisingVideo < ApplicationRecord
    mount_uploader :video, VideoUploader
end

app/models/landing_page/showcase.rb
class LandingPage::Showcase < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/landing_page/sponsors_and_supporter.rb
class LandingPage::SponsorsAndSupporter < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/controllers/landing_page/airfares_controller.rb
class LandingPage::AirfaresController < ApplicationController
  before_action do
    needs_to_be_admin("Você não tem permissão para isso!")
  end
  
  before_action :set_airfare, only: [:show, :edit, :update, :destroy]
  # before_action :admin_only, only: [:edit, :update, :destroy]

  # GET /airfares
  # GET /airfares.json
  def index
    @airfares =LandingPage::Airfare.all
  end

  # GET /airfares/1
  # GET /airfares/1.json
  def show
  end

  # GET /airfares/new
  def new
    @airfare =LandingPage::Airfare.new
  end

  # GET /airfares/1/edit
  def edit
  end

  # POST /airfares
  # POST /airfares.json
  def create
    @airfare =LandingPage::Airfare.new(airfare_params)

    respond_to do |format|
      if @airfare.save
        format.html { redirect_to sections_edit_path, notice: 'Passagem Aérea criada com sucesso.' }
        format.json { render :show, status: :created, location: @airfare }
      else
        format.html { render :new }
        format.json { render json: @airfare.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airfares/1
  # PATCH/PUT /airfares/1.json
  def update
    respond_to do |format|
      if @airfare.update(airfare_params)
        format.html { redirect_to sections_edit_path, notice: 'Passagem Aérea atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @airfare }
      else
        format.html { render :edit }
        format.json { render json: @airfare.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airfares/1
  # DELETE /airfares/1.json
  def destroy
    @airfare.destroy
    respond_to do |format|
      format.html { redirect_to sections_edit_path, notice: 'Passagem Aérea excluída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airfare
      @airfare =LandingPage::Airfare.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airfare_params
      params.require(:airfare).permit(:title, :phrase, :link)
    end
end

app/controllers/landing_page/event_notices_controller.rb
class LandingPage::EventNoticesController < ApplicationController
  before_action do
    needs_to_be_admin("Você não tem permissão para isso!")
  end
  before_action :set_event_notice, only: [:show, :edit, :update, :destroy]
  # before_action :admin_only, only: [:edit, :update, :destroy]

  # GET /event_notices
  # GET /event_notices.json
  def index
    @event_notices =LandingPage::EventNotice.all
  end

  # GET /event_notices/1
  # GET /event_notices/1.json
  def show
  end

  # GET /event_notices/new
  def new
    @event_notice =LandingPage::EventNotice.new
  end

  # GET /event_notices/1/edit
  def edit
  end

  # POST /event_notices
  # POST /event_notices.json
  def create
    @event_notice =LandingPage::EventNotice.new(event_notice_params)

    respond_to do |format|
      if @event_notice.save
        format.html { redirect_to sections_edit_path, notice: 'Notícia do Evento criada com sucesso.' }
        format.json { render :show, status: :created, location: @event_notice }
      else
        format.html { render :new }
        format.json { render json: @event_notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_notices/1
  # PATCH/PUT /event_notices/1.json
  def update
    respond_to do |format|
      if @event_notice.update(event_notice_params)
        format.html { redirect_to sections_edit_path, notice: 'Notícia do Evento atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @event_notice }
      else
        format.html { render :edit }
        format.json { render json: @event_notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_notices/1
  # DELETE /event_notices/1.json
  def destroy
    @event_notice.destroy
    respond_to do |format|
      format.html { redirect_to sections_edit_path, notice: 'Notícia do Evento excluída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_notice
      @event_notice =LandingPage::EventNotice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_notice_params
      params.require(:event_notice).permit(:title, :content, :image, :document)
    end
end

app/controllers/landing_page/event_realizers_controller.rb
class LandingPage::EventRealizersController < ApplicationController
  before_action do
    needs_to_be_admin("Você não tem permissão para isso!")
  end
  before_action :set_event_realizer, only: [:show, :edit, :update, :destroy]
  # before_action :admin_only, only: [:edit, :update, :destroy]

  # GET /event_realizers
  # GET /event_realizers.json
  def index
    @event_realizers = LandingPage::EventRealizer.all
    @event_realizer_title = LandingPage::EventRealizersTitle.all.first
  end

  # GET /event_realizers/1
  # GET /event_realizers/1.json
  def show
  end

  # GET /event_realizers/new
  def new
    @event_realizer = LandingPage::EventRealizer.new
  end

  # GET /event_realizers/1/edit
  def edit
  end

  # POST /event_realizers
  # POST /event_realizers.json
  def create
    @event_realizer = LandingPage::EventRealizer.new(event_realizer_params)

    respond_to do |format|
      if @event_realizer.save
        format.html { redirect_to sections_edit_path, notice: 'Realizador do Evento criado com sucesso.' }
        format.json { render :show, status: :created, location: @event_realizer }
      else
        format.html { render :new }
        format.json { render json: @event_realizer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_realizers/1
  # PATCH/PUT /event_realizers/1.json
  def update
    respond_to do |format|
      if @event_realizer.update(event_realizer_params)
        format.html { redirect_to sections_edit_path, notice: 'Realizador do Evento atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @event_realizer }
      else
        format.html { render :edit }
        format.json { render json: @event_realizer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_realizers/1
  # DELETE /event_realizers/1.json
  def destroy
    @event_realizer.destroy
    respond_to do |format|
      format.html { redirect_to sections_edit_path, notice: 'Realizador do Evento excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_realizer
      @event_realizer = LandingPage::EventRealizer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_realizer_params
      params.require(:event_realizer).permit(:image, :name, :description, :link)
    end
end

app/controllers/landing_page/event_realizers_titles_controller.rb
class LandingPage::EventRealizersTitlesController < ApplicationController
  before_action do
    needs_to_be_admin("Você não tem permissão para isso!")
  end
  before_action :set_event_realizers_title, only: [:show, :edit, :update, :destroy]
  # before_action :admin_only, only: [:edit, :update, :destroy]

  # GET /event_realizers_titles
  # GET /event_realizers_titles.json
  def index
    @event_realizers_titles = LandingPage::EventRealizersTitle.all
  end

  # GET /event_realizers_titles/1
  # GET /event_realizers_titles/1.json
  def show
  end

  # GET /event_realizers_titles/new
  def new
    @event_realizers_title = LandingPage::EventRealizersTitle.new
  end

  # GET /event_realizers_titles/1/edit
  def edit
  end

  # POST /event_realizers_titles
  # POST /event_realizers_titles.json
  def create
    @event_realizers_title = LandingPage::EventRealizersTitle.new(event_realizers_title_params)

    respond_to do |format|
      if @event_realizers_title.save
        format.html { redirect_to sections_edit_path, notice: 'Título de Realizadores do Evento criado com sucesso.' }
        format.json { render :show, status: :created, location: @event_realizers_title }
      else
        format.html { render :new }
        format.json { render json: @event_realizers_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_realizers_titles/1
  # PATCH/PUT /event_realizers_titles/1.json
  def update
    respond_to do |format|
      if @event_realizers_title.update(event_realizers_title_params)
        format.html { redirect_to sections_edit_path, notice: 'Título de Realizadores do Evento atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @event_realizers_title }
      else
        format.html { render :edit }
        format.json { render json: @event_realizers_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_realizers_titles/1
  # DELETE /event_realizers_titles/1.json
  def destroy
    @event_realizers_title.destroy
    respond_to do |format|
      format.html { redirect_to sections_edit_path, notice: 'Título de Realizadores do Evento excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_realizers_title
      @event_realizers_title = LandingPage::EventRealizersTitle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_realizers_title_params
      params.require(:event_realizers_title).permit(:title)
    end
end

app/controllers/landing_page/merchandising_videos_controller.rb
class LandingPage::MerchandisingVideosController < ApplicationController
  before_action do
    needs_to_be_admin("Você não tem permissão para isso!")
  end
  before_action :set_merchandising_video, only: [:show, :edit, :update, :destroy]
  # before_action :admin_only, only: [:edit, :update, :destroy]

  # GET /merchandising_videos
  # GET /merchandising_videos.json
  def index
    @merchandising_videos =LandingPage::MerchandisingVideo.all
  end

  # GET /merchandising_videos/1
  # GET /merchandising_videos/1.json
  def show
  end

  # GET /merchandising_videos/new
  def new
    @merchandising_video =LandingPage::MerchandisingVideo.new
  end

  # GET /merchandising_videos/1/edit
  def edit
  end

  # POST /merchandising_videos
  # POST /merchandising_videos.json
  def create
    @merchandising_video =LandingPage::MerchandisingVideo.new(merchandising_video_params)

    respond_to do |format|
      if @merchandising_video.save
        format.html { redirect_to sections_edit_path, notice: 'Video de Divulgação criado com sucesso.' }
        format.json { render :show, status: :created, location: @merchandising_video }
      else
        format.html { render :new }
        format.json { render json: @merchandising_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merchandising_videos/1
  # PATCH/PUT /merchandising_videos/1.json
  def update
    respond_to do |format|
      if @merchandising_video.update(merchandising_video_params)
        format.html { redirect_to sections_edit_path, notice: 'Video de Divulgação atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @merchandising_video }
      else
        format.html { render :edit }
        format.json { render json: @merchandising_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchandising_videos/1
  # DELETE /merchandising_videos/1.json
  def destroy
    @merchandising_video.destroy
    respond_to do |format|
      format.html { redirect_to sections_edit_path, notice: 'Video de Divulgação excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchandising_video
      @merchandising_video =LandingPage::MerchandisingVideo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merchandising_video_params
      params.require(:merchandising_video).permit(:title, :video)
    end
end

app/controllers/landing_page/showcases_controller.rb
class LandingPage::ShowcasesController < ApplicationController
  before_action do
    needs_to_be_admin("Você não tem permissão para isso!")
  end
  before_action :set_showcase, only: [:show, :edit, :update, :destroy]
  # before_action :admin_only, only: [:edit, :update, :destroy]

  # GET /showcases
  # GET /showcases.json
  def index
    @showcases =LandingPage::Showcase.all
  end

  # GET /showcases/1
  # GET /showcases/1.json
  def show
  end

  # GET /showcases/new
  def new
    @showcase =LandingPage::Showcase.new
  end

  # GET /showcases/1/edit
  def edit
  end

  # POST /showcases
  # POST /showcases.json
  def create
    @showcase =LandingPage::Showcase.new(showcase_params)

    respond_to do |format|
      if @showcase.save
        format.html { redirect_to sections_edit_path, notice: 'Vitrine criada com sucesso.' }
        format.json { render :show, status: :created, location: @showcase }
      else
        format.html { render :new }
        format.json { render json: @showcase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /showcases/1
  # PATCH/PUT /showcases/1.json
  def update
    respond_to do |format|
      if @showcase.update(showcase_params)
        format.html { redirect_to sections_edit_path, notice: 'Vitrine atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @showcase }
      else
        format.html { render :edit }
        format.json { render json: @showcase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /showcases/1
  # DELETE /showcases/1.json
  def destroy
    @showcase.destroy
    respond_to do |format|
      format.html { redirect_to sections_edit_path, notice: 'Vitrine excluída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_showcase
      @showcase =LandingPage::Showcase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def showcase_params
      params.require(:showcase).permit(:title, :subtitle, :phrase, :image)
    end
end

app/views/landing_page/static_pages/landing_page.html.erb
<body class="home">
    <section id="section-main" class="main-session" style="background-image: url(<%=@showcase.image.url%>);">
        <div class="container-home">
            <div class="home-esquerda">
                <h2><%=@showcase.title%> </h2>
                <h1><%=@showcase.subtitle%></h1>
                <h3><%=@showcase.phrase%></h3>
            </div>
            <div class="home-direita ">
                <%if logged_in? and admin_user_logged? %>
                    <p><%=link_to "Área do congressista", users_path, class: "area-do-congressista-button"%></p>
                <%elsif logged_in?%>
                    <p><%=link_to "Área do congressista", @current_user, class: "area-do-congressista-button"%></p>
                <%else%>
                    <p><%=link_to "Área do congressista", login_path, class: "area-do-congressista-button"%></p>
                <%end%>
            </div>
        </div>
        <div class='icon-scroll'></div>
    </section>

    <section  id="section-event" class="evento-session sections-home-table-cell">
        <div class="home-esquerda">
            <h4><%=@the_event.title%></h4>
            <p><%=@the_event.content%></p>
        </div>
        <div class="home-direita">
            <h2><%=@the_event.days%></h2>
            <div><span>de </span><h3> <%=@the_event.month%></h3></div>
            <div><span>em </span><h3> <%=@the_event.locality%></h3></div>
        </div>
    </section>

    <section id="section-pass" class="passport-session">
        <div class="container-passport">
            <div class="passport-left">
            <%= image_tag("passaporte.png", :alt => "logo da plataforma de passaporte", :class => "logo-passport") %>
            </div>

            <div class="passport-right">
                    <div class="text-passport">
                        <h2><%=@airfare.title%></h2>
                        <p><%=@airfare.phrase%></p>
                        <%= link_to "http://#{@airfare.link}" do %>
                            <button class="price-button">Confira os preços </button>
                        <% end %>
                    </div>
            </div>
        </div>
    </section>

    <section id="section-pales" class="palestrantes-session sections-home-table-cell">
        <div class="home-esquerda">
            <h2><%=@the_speakers.title%></h2>
            <p><%=@the_speakers.description%></p>
            <%= link_to @the_speakers.document.url, target: :_blank do %>
                <p><button class="confira-ja-button">Confira Já</button></p>
            <% end %>
        </div>
        <div class="home-direita"  style="background-image: url(<%=@the_speakers.image.url%>);">
        </div>
        
    </section>

    <section id="section-edi" class="editais-session sections-home-table-cell">
        <div class="home-esquerda"  style="background-image: url(<%=@event_notices.image.url%>);">
        </div>
        <div class="home-direita">
            <h2><%=@event_notices.title%></h2>
            <p><%=@event_notices.content%></p>
            <%= link_to @event_notices.document.url, target: :_blank do %>
                <p><button class="confira-ja-button">Confira Já</button></p>
            <% end %>
        </div>
    </section>

    <section id="section-revo" class ="revolucao-session">
        <div class="revolucao-centro">
            <h2><%=@video.title%></h2>
            <div class="revolucao-video" controls>
                <%= video_tag @video.video.url, class: "revolucao-video", controls: true %>
            </div>
        </div>
    </section>

    <section id="section-reali" class="realizadores-session">
        <div class="realizadores-middle">
            <h2><%= @event_realizers_title %></h2>
            <div id="realizadorslider">
                <% @event_realizers.each do |event|%>
                    <div class="item">
                        <%= link_to "http://#{event.link}" do %>
                            <%= image_tag(event.image.url, alt: "logo do enec", class: "logo-enec") %>
                        <% end %>
                        <p><%= event.description %></p>
                        <h3><%= event.name %></h3>
                    </div>
                <% end %>
            </div>
        </div>
    </section>

<section id="section-patro" class="patrocinadores-session sections-home-table-cell">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    <div class="home-middle">
        <h2><%=@sponsor_and_supporters_title%>  </h2>
        <div class="logos-patrocinadores">
            <% @sponsors_and_supporters.each do |ss| %>
                <%= link_to "http://#{ss.link}" do %>
                    <%= image_tag(ss.image.url, alt: "logo do patrocinador", class: "logo-patrocinador") %>
                <% end %>
            <%end%>
    </section>

    <section id="section-contact" class="contato-session sections-home-table-cell">
        <div class="home-middle">
            <h2>Contato</h2>
            <%=form_with(url: send_contact_email_path, remote: true)  do |f| %>
                <p><%= f.text_field :name, placeholder: "Nome", class: "input" %></p>
                <p><%= f.text_field :email,placeholder: "E-mail",  class: "input" %></p>
                <p><%= f.text_area :message,placeholder: "Mensagem", class: "input mensagem" %></p>
                <input type="submit" value="Enviar" class="form-button">
            <% end %>
        </div>
    </section>
    <% if notice.present? %>
        <script>
            $(document).ready(function() {
                alert("<%= notice %>");
            });
        </script>   
    <% end %>
</body>

app/views/landing_page/static_pages/sections_edit.html.erb
<section class="index-sections">
  <div class="container-table">
    <h1>Lista de Seções</h1>
    <div class="table">
      <table>
        <thead>
          <tr>
            <th>Section</th>
            <th colspan="1">Ações</th>
          </tr>
        </thead>

        <tbody>
            <tr>
              <td>Sessão Principal</td>
              <td class="td-ações td-editar">
                <%= link_to 'Editar', edit_showcase_path(@showcase) %><%= link_to edit_showcase_path(@showcase) do %><%= image_tag("edit.png", :alt => "imagem de editar", :class => "img-editar img-table") %><%end%>
              </td>
            <tr>
              <td>Sessão "O Evento"</td>
              <td class="td-ações td-editar">
                <%= link_to 'Editar', edit_the_event_path(@the_event) %><%= link_to edit_the_event_path(@the_event) do %><%= image_tag("edit.png", :alt => "imagem de editar", :class => "img-editar img-table") %><%end%>
              </td>
            <tr>
              <td>Sessão "Passaporte"</td>
              <td class="td-ações td-editar">
                <%= link_to 'Editar', edit_airfare_path(@airfare) %><%= link_to edit_airfare_path(@airfare) do %><%= image_tag("edit.png", :alt => "imagem de editar", :class => "img-editar img-table") %><%end%>
              </td>
            </tr>
            <tr>
              <td>Sessão "Os Palestrantes"</td>
              <td class="td-ações td-editar">
                <%= link_to 'Editar', edit_the_speaker_path(@the_speakers) %><%= link_to edit_the_speaker_path(@the_speakers) do %><%= image_tag("edit.png", :alt => "imagem de editar", :class => "img-editar img-table") %><%end%>
              </td>
            </tr>
            <tr>
              <td>Sessão "Editais do Evento"</td>
              <td class="td-ações td-editar">
                <%= link_to 'Editar', edit_event_notice_path(@event_notices) %><%= link_to edit_event_notice_path(@event_notices) do %><%= image_tag("edit.png", :alt => "imagem de editar", :class => "img-editar img-table") %><%end%>
              </td>
            </tr>
            <tr>
              <td>Sessão de Video</td>
              <td class="td-ações td-editar">
                <%= link_to 'Editar', edit_merchandising_video_path(@video) %><%= link_to edit_merchandising_video_path(@video) do %><%= image_tag("edit.png", :alt => "imagem de editar", :class => "img-editar img-table") %><%end%>
              </td>
            </tr>
            <tr>
              <td>Sessão "Realizadores do Evento"</td>
              <td class="td-ações td-editar">
                <%= link_to 'Editar', event_realizers_path %><%= link_to event_realizers_path do %><%= image_tag("edit.png", :alt => "imagem de editar", :class => "img-editar img-table") %><%end%>
              </td>
            </tr>
            <tr>
              <td>Sessão "Patrocinadores e Apoiadores"</td>
              <td class="td-ações td-editar">
                <%= link_to 'Editar', sponsors_and_supporters_path %><%= link_to sponsors_and_supporters_path do %><%= image_tag("edit.png", :alt => "imagem de editar", :class => "img-editar img-table") %><%end%>
              </td>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/landing_page/static_pages/send_email.js.erb
alert("Email enviado com sucesso!");