config/routes.rb
Rails.application.routes.draw do
  scope(path_names: { new: 'criar', edit: 'editar' }) do
    
    scope module: :landing_page do
      root to: 'static_pages#landing_page'
    end

    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy', as: 'logout'
    
    get 'usuarios/:id/alteracao-de-senha', to: "users#change_password"
    post 'usuarios/:id/alteracao-de-senha', to: "users#change_password", as: 'change_password'
    get 'usuarios/:id/selecao-de-pacote', to: "users#term_agreement"
    post 'usuarios/:id/selecao-de-pacote', to: "users#term_agreement", as: 'term_agreement'
    
    resources :users, path: 'usuarios'
    resources :interests, path: 'juros'
    resources :parcels, path: 'parcelas'
      post '/parcelas/update_status', to: 'parcels#update_status', as: 'update_parcel_status'
    resources :payments, path: 'pagamentos'
      get '/retorna_parcelas', to: 'payments#get_parcelas'
    resources :packages, path: 'pacotes'
    resources :ies, path: 'instituicoes-de-ensino-superior'
    resources :lots, path: 'lotes'
    
    scope module: :landing_page do
      get '/edicao-secoes', to: 'static_pages#sections_edit', as: 'sections_edit'
      post '/contato/enviar-email', to: 'static_pages#send_email', as: 'send_contact_email'
      resources :sponsors_and_supporters_titles, path: 'titulo-de-patrocionadores-e-apoiadores'
      resources :event_realizers_titles, path: 'titulo-de-realizadores-do-evento'
      resources :sponsors_and_supporters, path: 'patrocionadores-e-apoiadores'
      resources :event_realizers, path: 'realizadores-do-evento'
      resources :merchandising_videos, path: 'video-de-divulgacao'
      resources :event_notices, path: 'noticias-do-evento'
      resources :the_speakers, path: 'palestrantes'
      resources :airfares, path: 'passagens-aereas'
      resources :the_events, path: 'eventos'
      resources :showcases, path: 'vitrine'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :package
  belongs_to :user
  has_many :parcels, dependent: :destroy

  validates :package_id, presence: true
  validates :payment_option, presence: true
  validates :parceling_option, presence: true

  before_create :calculate_value

  enum payment_option: {"boleto": 1 , "cartao": 2}
  enum parceling_options: {"1x sem juros": 1 ,"2x sem juros": 2 ,"3x sem juros": 3 ,"4x sem juros": 4 ,"5x sem juros": 5 ,"6x com juros no cartão(somente no cartão)": 6 ,"7x com juros no cartão(somente no cartão)": 7 ,"8x com juros no cartão(somente no cartão)": 8 ,"9x com juros no cartão(somente no cartão)": 9 ,"10x com juros no cartão(somente no cartão)": 10}

  def generate_parcels
    quantity = parceling_option_before_type_cast

    if !(payment_option == 'cartao' && quantity > 5)

      parcel_general_value = (value/quantity).round(2)
      total_value = value
      quantity.times do |i|
        @parcel = Parcel.create(
          value: parcel_general_value,
          payment: self,
          status: 4
          )
          total_value -= parcel_general_value
      end

      # Se na hora de dividir o valor das parcelas der um valor
      # negativo no valor do pagamento, quer dizer que as parcelas
      # estão cobrando, ao todo, um valor maior que o pagamento previsto.
      # Por isso, isso é checado e tratado fazendo a última parcela ter
      # valor um pouco menor, nesse tipo de caso.

      if total_value != 0
        @parcel.update(value: (@parcel.value + total_value).round(2))
      end

    else  # Com Juros compostos, a parcela tem que ser calculada por partes.
      base_value = package.value
      parcel_base_value = (base_value/quantity).round(2)
      parcel_base_value += (parcel_base_value * BigDecimal.new("0.0499")) + BigDecimal.new("0.50")

      total_value = value

      5.times do |i|
        parcel = Parcel.create(
          value: parcel_base_value,
          payment: self,
          status: 4
          )
          total_value -= parcel_base_value
      end

      parcel_compound_value = (total_value/(quantity-5)).round(2)

      (quantity-5).times do |i|
        @parcel = Parcel.create(
          value: parcel_compound_value,
          payment: self,
          status: 4
          )
          total_value -= parcel_compound_value
      end
      
      # Veja explicação para esse if no bloco de comentário acima.
      if total_value != 0
        @parcel.update(value: (@parcel.value + total_value).round(2))
      end
    end
  end

  private
    def calculate_value
      if self.valid?
        quantity_parcels = parceling_option_before_type_cast.to_i
      
        if payment_option == 'boleto'
          self.value += quantity_parcels * BigDecimal.new("3.95")

        elsif payment_option == 'cartao'
          value_without_rate = value
          self.value += value * BigDecimal.new("0.0499") 
          self.value += quantity_parcels * BigDecimal.new("0.50")
          
          if quantity_parcels > 5
            parcel_value = (value_without_rate/quantity_parcels).round(2)
            self.value += ((parcel_value * (1 + BigDecimal.new("0.025")) ** (quantity_parcels-5)) - parcel_value) * (quantity_parcels-5)
          end
        end
      end
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  require 'sendgrid-ruby'
  
  include PaymentsHelper
  include ActionView::Helpers::NumberHelper

  before_action except: [:show, :new, :create, :get_parcelas] do
    needs_to_be_admin("Você não tem permissão para isso!")
  end

  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action only: [:show] do
    if current_user.id != @payment.user_id
      needs_to_be_admin("Você não tem permissão para isso!")
    end
  end
  # before_action :admin_only, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    info = params.require(:subscription).permit(:name, :cpf, :package_id, :email, :telephone, :pagamento, :parcelas)
    info.values.each do |i|
      if i.nil?
        redirect_to new_payment_path, notice: "Preencha todos os campos!"
      end
    end

    package = Package.find(info[:package_id])
    payment = Payment.new(
      value: package.value,
      payment_option: info[:pagamento],
      parceling_option: info[:parcelas],
      user: current_user,
      package: package
    )
    if payment.save
      sendgrid = SendGrid::Client.new do |c|
        c.api_key = ENV["sendgrid_api_key"]
      end
      
      current_user.update(
        name: info[:name],
        cpf: info[:cpf],
        email: info[:email],
        telephone: info[:telephone]
      )
      payment.generate_parcels
      current_user.update(package_id: package.id)
      
      info[:id] = current_user.id
      info[:package] = package
      PaymentMailer.notify_admin_about_payment(info).deliver_later
      PaymentMailer.notify_user_about_payment(current_user).deliver_later
      
      @user_info = user_info
      @user = User.find(user_info[:id])
      
      email = SendGrid::Mail.new do |m|
        m.to      = 'inscricaoenec@fenec.com.br'
        m.from    = 'inscricaoenec@fenec.com.br'
        m.subject = "#{@user.name} criou um pagamento!"
        m.html    = 
        "<h1>Novo Pagamento Registrado!</h1>

        <p>
            Olá! O usuário #{@user.name} preencheu o formulário de pagamento.
        </p>
        
        <h2>Dados do Cliente</h2>
        
        <ul>
            <li>CPF: #{info[:cpf]}</li>
            <li>Nome: #{info[:name]}</li>
            <li>Email: #{info[:email]}</li>
            <li>Telefone: #{info[:telephone]}</li>
            <li>Pacote: #{info[:package].name}</li>
            <li>Forma de Pagamento: #{info[:pagamento]}</li>
            <li>Número de Parcelas: #{info[:parcelas]}</li>
        </ul>
        
        <p>
            #{view_context.link_to "Clique aqui", @user} para acessar o perfil deste usuário.
        </p>"
        
        m.text    = 
         "Novo Pagamento Registrado!

          
              Olá! O usuário #{@user.name} preencheu o formulário de pagamento.
          
          
          Dados do Cliente
          
          
              CPF: #{info[:cpf]}
              Nome: #{info[:name]}
              Email: #{info[:email]}
              Telefone: #{info[:telephone]}
              Pacote: #{info[:package].name}
              Forma de Pagamento: #{info[:pagamento]}
              Número de Parcelas: #{info[:parcelas]}
          
          
          
              #{view_context.link_to "Clique aqui", @user} para acessar o perfil deste usuário.
          "
      end
      
      email_user = SendGrid::Mail.new do |m|
        m.to      = @user.email
        m.from    = 'inscricaoenec@fenec.com.br'
        m.subject = "Solicitação de Pagamento registrada"
        m.html    = 
        "
        <p>
            Olá #{@user.name}. sua solicitação de pagamento foi registrada com sucesso!
        </p>
        "
        
        m.text    = 
         "
             Olá #{@user.name}. sua solicitação de pagamento foi registrada com sucesso!
         "
      end
      
      sendgrid.send(email)
      sendgrid.send(email_user)

      redirect_to payment
    else
      flash.notice = payment.errors
      redirect_to new_payment_path
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Pagamento atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Pagamento excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  def get_parcelas
    @result = parcelas(params[:package_id], params[:pagamento])
    
    render json: @result
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:package_id, :payment_option, :parceling_option, :user_id)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
    def pretty_payment_option(payment)
        if payment.payment_option == 'boleto'
            return 'Boleto Bancário'
        else
            return 'Cartão de Crédito'
        end
    end

    def user_package(user)
        user_package_id = user.package_id
        package = Package.find(user_package_id)
        return package
    end

# ************************************************
# * MÉTODOS FEITOS PARA PÁGINA DE NOVO PAGAMENTO *
# ************************************************
    # retorna os pacotes associados ao lote do usuario
    def package_select(user)
        @packages = Package.where(lot_id: user.lot_id).includes(:lot)
        
        @packages.all.collect { |p| ["#{p.lot.name}, #{p.name},
        #{number_to_currency(p.value, :unit => "R$ ", :separator => ",",
        :delimiter => ".")}", p.id] }
    end

    def parcelas(package_id, pagamento)
        package = Package.find(package_id)
        
        # todos os pagamentos contam com uma taxa base de 5%
        valor = package.value
        valor_boleto = BigDecimal.new("3.95")
        valor_monetario = number_to_currency(valor, :unit => "R$ ", 
                                            :separator => ",",
                                            :delimiter => ".")
        
        parcelas_simples = [
            { parcelas: 1, detalhes: "1x de #{ package.value + valor_boleto}, total: #{ package.value + valor_boleto }" },
            { parcelas: 2, detalhes: "2x de #{ valor_monetario_parcelado(valor + 2*valor_boleto, 2) },
            total: #{ package.value + 2*valor_boleto }" },
            { parcelas: 3, detalhes: "3x de #{ valor_monetario_parcelado(valor + 3*valor_boleto, 3) },
            total: #{ package.value + 3*valor_boleto }" },
            { parcelas: 4, detalhes: "4x de #{ valor_monetario_parcelado(valor + 4*valor_boleto, 4) },
            total: #{ package.value + 4*valor_boleto }" },
            { parcelas: 5, detalhes: "5x de #{ valor_monetario_parcelado(valor + 5*valor_boleto, 5) },
            total: #{ package.value + 5*valor_boleto }" },
            ]
        
        if pagamento == "boleto"
        return parcelas_simples
        elsif pagamento == "cartao"
        # pagamentos no cartão com mais de 5 parcelas tem juros compostos de 3% sobre o valor do pacote
        
        parcelas_compostas = parcelas_simples
        
        parcelas_compostas.append({ parcelas: 6, detalhes: "6x de 
            #{ parcela_com_juros_compostos(total_com_juros_compostos(valor_com_taxa, 6), 6) },
            total: #{ total_monetario_com_juros_compostos(total_com_juros_compostos(valor_com_taxa, 6)) }" })
        
        parcelas_compostas.append({ parcelas: 7, detalhes: "7x de 
            #{ parcela_com_juros_compostos(total_com_juros_compostos(valor_com_taxa, 7), 7) },
            total: #{ total_monetario_com_juros_compostos(total_com_juros_compostos(valor_com_taxa, 7)) }" })
            
        parcelas_compostas.append({ parcelas: 8, detalhes: "8x de 
            #{ parcela_com_juros_compostos(total_com_juros_compostos(valor_com_taxa, 8), 8) },
            total: #{ total_monetario_com_juros_compostos(total_com_juros_compostos(valor_com_taxa, 8)) }" })
            
        parcelas_compostas.append({ parcelas: 9, detalhes: "9x de 
            #{ parcela_com_juros_compostos(total_com_juros_compostos(valor_com_taxa, 9), 9) },
            total: #{ total_monetario_com_juros_compostos(total_com_juros_compostos(valor_com_taxa, 9)) }" })
            
        parcelas_compostas.append({ parcelas: 10, detalhes: "10x de 
            #{ parcela_com_juros_compostos(total_com_juros_compostos(valor_com_taxa, 10), 10) },
            total: #{ total_monetario_com_juros_compostos(total_com_juros_compostos(valor_com_taxa, 10)) }" })
        
        return parcelas_compostas
        end
        [{parcelas: "", detalhes: "Selecione forma de pagamento"}]
    end

    def valor_monetario_parcelado(valor, parcelas)
        number_to_currency((valor / parcelas), :unit => "R$ ", 
                                            :separator => ",",
                                            :delimiter => ".")
    end

    def total_com_juros_compostos(capital_inicial, periodo)
        capital_inicial * (1 + 0.03) ** periodo
    end

    def total_monetario_com_juros_compostos(valor)
        number_to_currency(valor, 
                                :unit => "R$ ", 
                                :separator => ",",
                                :delimiter => ".")
    end

    def parcela_com_juros_compostos(valor, parcelas)
        number_to_currency((valor / parcelas), 
                                :unit => "R$ ", 
                                :separator => ",",
                                :delimiter => ".")
    end
end

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :package_id, value: user_package(@current_user).id %>
  </div>

  <div class="field">
    <%= form.label :payment_option %>
    <%= form.select :payment_option, Payment.payment_options.keys, {include_blank: true}%>
  </div>

  <div class="field">
    <%= form.label :parceling_option %>
    <%= form.select :parceling_option, Payment.parceling_options.keys, {include_blank: true}%>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.hidden_field :user_id, value: @current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Package</th>
      <th>Payment option</th>
      <th>Parceling option</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.package %></td>
        <td><%= payment.payment_option %></td>
        <td><%= payment.parceling_option %></td>
        <td><%= payment.user %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<body class="sessions">
  <section class="container-sessions">


    <h2>Pagamento</h2>

    <%= form_for :subscription, url: payments_path do |f| %>
      <div class="field">
        <p><%= f.label :CPF %></p>
        <%= f.text_field :cpf, value: current_user.cpf, required: true %>
      </div>

      <div class="field">
        <p><%= f.label :Nome %></p>
        <%= f.text_field :name, value: current_user.name, required: true %>
      </div>
      
      <div class="field">
        <p><%= f.label :Email %></p>
        <%= f.email_field :email, value: current_user.email, required: true %>
      </div>      
      
      <div class="field">
        <p><%= f.label :Telefone %></p>
        <%= f.text_field :telephone, value: current_user.telephone, required: true %>
      </div>        

      <div class="fieldPag">
        <p><%= f.label :Pacote %></p>
        <%= select(:subscription, :package_id, package_select(current_user), required: true) %>
      </div>      
      
      <div class="fieldPag">
        <p><%= f.label "Forma de pagamento" %></p>
        <%= select(:subscription, :pagamento, 
            options_for_select(
              [ 
                 ["Selecione forma de pagamento", ""], 
                 ["Cartão de Crédito", "cartao"], ["Boleto bancário", "boleto"],
              ], ["Selecione forma de pagamento", ""]), required: true) %>
      </div>
      
      <div class="fieldPag">
        <p><%= f.label "Nº de parcelas" %></p>
        <%= select(:subscription, :parcelas, 
            [ ["Selecione forma de pagamento", ""] ], required: true) %>
      </div>
      
      <div class="actions">
        <%= f.submit "Enviar" %>
      </div>

    <% end %>
  </section>
</body>

<script>
  $( "#subscription_package_id" ).change(function() {
  	
  	$( "#subscription_parcelas" ).html('');
  	$( "#subscription_parcelas" ).append('<option value="">' + 'Selecione forma de pagamento' + '</option>')
  
    $( "#subscription_pagamento" ).html('');
    $( "#subscription_pagamento" ).append('<option value="">' + 'Selecione forma de pagamento' + '</option>')
    $( "#subscription_pagamento" ).append('<option value="cartao">' + 'Cartão de Crédito' + '</option>')
    $( "#subscription_pagamento" ).append('<option value="boleto">' + 'Boleto bancário' + '</option>')
  });
</script>

<script>
  $( "#subscription_pagamento" ).change(function() {
  	package_id = $( "#subscription_package_id" ).val();
  	pagamento = $(this).val();
  	
  	$( "#subscription_parcelas" ).html('');
  	$( "#subscription_parcelas" ).prop('disabled', true);
  
  	$.ajax({
  	  type:"GET",
  	  url:"/retorna_parcelas",
  	  dataType:"json",
  	  data: { package_id: package_id, pagamento: pagamento },
  	  success:function(result){
  	    //adicionar opções ao dropdown
  	    $( "#subscription_parcelas" ).html('');
  	    for (i = 0; i < result.length; i++) {
  		    $( "#subscription_parcelas" ).append('<option value="' + result[i].parcelas + '">' + result[i].detalhes + '</option>')
  		  }
  		  $( "#subscription_parcelas" ).prop('disabled', false);
  	  }
  	})
  });
</script>

app/views/payments/show.html.erb
<section class="index-sections">
  <div class="container-table">
    <p id="notice"><%= notice %></p>
    <h2>
      Pacote:
      <%= @payment.package.name %>
    </h2>

    <h2>
      Valor Total:
      <%= number_to_currency(@payment.value, :unit => "R$ ", :separator => ",",
          :delimiter => ".") %>
    </h2>

    <h2>
      Forma de Pagamento:
      <%= pretty_payment_option(@payment) %>
    </h2>

    <h2>
      Opção de Parcelamento:
      <%= @payment.parceling_option %> vezes
    </h2>

    <div class="titulo-com-edit">
      <button><%= link_to 'Voltar', @payment.user %></button>
    </div>
    <div class="table">
      <table>
        <thead>
          <tr>
            <th> Valor </th>
            <th> Status </th>
          </tr>
        </thead>
        <tbody>
          <% @payment.parcels.each do |parcel| %>
            <tr>
              <td><%= number_to_currency(parcel.value, :unit => "R$ ", :separator => ",",
          :delimiter => ".") %></td>
              <td>
                <% if current_user.admin? %>
                  <%= form_with model: parcel do |form| %>
                    <%= form.select :status, Parcel.statuses.keys, {}, id: "parcel_#{parcel.id}", class: 'parcel-change-status' %>
                  <% end %>
                <% else %>
                  <%= parcel.status %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</section>