config/routes.rb
Rails.application.routes.draw do
  scope(path_names: { new: 'criar', edit: 'editar' }) do
    
    scope module: :landing_page do
      root to: 'static_pages#landing_page'
    end

    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy', as: 'logout'
    
    get 'usuarios/:id/alteracao-de-senha', to: "users#change_password"
    post 'usuarios/:id/alteracao-de-senha', to: "users#change_password", as: 'change_password'
    get 'usuarios/:id/selecao-de-pacote', to: "users#term_agreement"
    post 'usuarios/:id/selecao-de-pacote', to: "users#term_agreement", as: 'term_agreement'
    
    resources :users, path: 'usuarios'
    resources :interests, path: 'juros'
    resources :parcels, path: 'parcelas'
      post '/parcelas/update_status', to: 'parcels#update_status', as: 'update_parcel_status'
    resources :payments, path: 'pagamentos'
      get '/retorna_parcelas', to: 'payments#get_parcelas'
    resources :packages, path: 'pacotes'
    resources :ies, path: 'instituicoes-de-ensino-superior'
    resources :lots, path: 'lotes'
    
    scope module: :landing_page do
      get '/edicao-secoes', to: 'static_pages#sections_edit', as: 'sections_edit'
      post '/contato/enviar-email', to: 'static_pages#send_email', as: 'send_contact_email'
      resources :sponsors_and_supporters_titles, path: 'titulo-de-patrocionadores-e-apoiadores'
      resources :event_realizers_titles, path: 'titulo-de-realizadores-do-evento'
      resources :sponsors_and_supporters, path: 'patrocionadores-e-apoiadores'
      resources :event_realizers, path: 'realizadores-do-evento'
      resources :merchandising_videos, path: 'video-de-divulgacao'
      resources :event_notices, path: 'noticias-do-evento'
      resources :the_speakers, path: 'palestrantes'
      resources :airfares, path: 'passagens-aereas'
      resources :the_events, path: 'eventos'
      resources :showcases, path: 'vitrine'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lot.rb
class Lot < ApplicationRecord
    mount_uploader :term, TermUploader
    enum payment_status: {
        "Ativo": 1, 
        "Não Ativo": 2
    }
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
  before_action do
    needs_to_be_admin("Você não tem permissão para isso!")
  end
  before_action :set_lot, only: [:show, :edit, :update, :destroy]
  # before_action :admin_only, only: [:show, :edit, :update, :destroy]

  # GET /lots
  # GET /lots.json
  def index
    @lots = Lot.all
  end

  # GET /lots/1
  # GET /lots/1.json
  def show
  end

  # GET /lots/new
  def new
    @lot = Lot.new
  end

  # GET /lots/1/edit
  def edit
  end

  # POST /lots
  # POST /lots.json
  def create
    @lot = Lot.new(lot_params)

    respond_to do |format|
      if @lot.save
        format.html { redirect_to @lot, notice: 'Lote criado com sucesso.' }
        format.json { render :show, status: :created, location: @lot }
      else
        format.html { render :new }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lots/1
  # PATCH/PUT /lots/1.json
  def update
    respond_to do |format|
      if @lot.update(lot_params)
        format.html { redirect_to @lot, notice: 'Lote atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @lot }
      else
        format.html { render :edit }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lots/1
  # DELETE /lots/1.json
  def destroy
    @lot.destroy
    respond_to do |format|
      format.html { redirect_to lots_url, notice: 'Lote excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lot
      @lot = Lot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lot_params
      params.require(:lot).permit(:name, :status, :link, :term)
    end
end

app/helpers/lots_helper.rb
module LotsHelper
end

app/views/lots/_form.html.erb
<%= form_with(model: lot, local: true) do |form| %>
  <% if lot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lot.errors.count, "error") %> prohibited this lot from being saved:</h2>

      <ul>
      <% lot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  


  

  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :name, class: "input-texto"  %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status, class: "input-texto"  %>
  </div>

  <div class="field send-file" id="file_field">
    <%= form.file_field :term, id:"term_label" %>
    <label for="term_label">Enviar Termo</label>
    <%= form.hidden_field :file_cache %>
  </div>
  
  <div class="field">
    <%= form.label :link, "Link (sem http://)" %>
    <%= form.text_field :link, class: "input-texto" %>
  </div>

  <div class="actions">
    <%= form.submit "Cadastrar" %>
    <%= link_to 'Voltar', lots_path %>
  </div>

  
<% end %>

app/views/lots/edit.html.erb
<section class="edit-sections">
    <div class="container-table">
        <h1>Edição de Lotes</h1>
        <div class="form-edit-section">
            <%= render 'form', lot: @lot  %>
        </div>
    </div>
</section>

app/views/lots/index.html.erb
<section class="index-sections">
  <div class="container-table">
  <p id="notice"><%= notice %></p>
    <h1>Lista de Lotes</h1>
    <div class="titulo-com-edit">
      <button><%= link_to 'Novo Lote', new_lot_path %></button>
    </div>
    <div class="table">
      <table>
        <thead>
          <tr>
            <th>Nome</th>
            <th>Status</th>
            <th>Link</th>
            <th>Ver</th>
            <th>Editar</th>
            <th>Excluir</th>
            
          </tr>
        </thead>

        <tbody>
          <% @lots.each do |lot| %>
            <tr>
              <td><%= lot.name %></td>
              <td><%= lot.status %></td>
              <td><%= lot.link %></td>
            
              <td class="td-ações td-editar"><%= link_to 'Ver', lot %></td>
              <td class="td-ações td-editar"><%= link_to 'Editar', edit_lot_path(lot) %></td>
              <td class="td-ações td-editar"> <%= link_to 'Excluir', lot, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/lots/new.html.erb
<body class="sessions">
  <section class="container-sessions">
    <div class="campos-cadastro">
      <h2>Cadastro de Lotes</h2>
      <%= render 'form', lot: @lot %>
    </div>
  </section>
</body>

app/views/lots/show.html.erb
<!--<body class="sessions">
  <section class="container-sessions">

  <p id="notice"><%= notice %></p>

  <div class="boxLoteShow">
    <h3>Lote:</h3>
    <p><%= @lot.name %></p>
  </div>

  <div class="boxLoteShow">
    <h3>Link do Google Form:</h3>
    <p><%= @lot.link %></p>
  </div>

  <div class="boxLoteShow">
    <h3>Status:</h3>
    <p><%= @lot.status %></p>
  </div>

  <div class="boxLoteShow">
    <h3>Termos e Condições:</h3>
    <p><%= link_to 'PDF', @lot.term.url, target: :_blank %></p>
  </div>



  </section>
</body>
-->
<section class="edit-sections">
  <div class="container-table">
    <p id="notice"><%= notice %></p>
    <h1><%= @lot.name %></h1>
    <div class="form-edit-section">

      <div class="field">
        <label>Link do Google Form</label>
        <p><%= @lot.link %></p>
      </div>

      <div class="field">
        <label>Status</label>
        <p><%= @lot.status %></p>
      </div>

      <div class="field">
        <label>Termos e Condições:</label>
        <%= link_to 'PDF', @lot.term.url, target: :_blank, class:"link-field" %>
      </div>

      <br><br>
      <%= link_to 'Voltar', lots_path, class:"link-show-section" %>
    </div>
  </div>
</section>